
export const environmentAemet = {
  token:'eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjYXN0cm9qb3JnZWxlb25hcmRvY0BnbWFpbC5jb20iLCJqdGkiOiI3MTdlZDBhOC0xYTNmLTRlZjItYTEwNi0wYjYwNzNiYjhkODciLCJpc3MiOiJBRU1FVCIsImlhdCI6MTcxNTI2NjcwNiwidXNlcklkIjoiNzE3ZWQwYTgtMWEzZi00ZWYyLWExMDYtMGI2MDczYmI4ZDg3Iiwicm9sZSI6IiJ9.1s8Q1tSSGBkJPHUG3MzKA_NpOyji21t_D7eE4Tt0GzY',
  apiAemet:'https://opendata.aemet.es/opendata/api/prediccion/especifica/municipio/diaria/'
}
